### PR TITLE
Support multiple reverse pointers against a single ip

### PR DESCRIPTION
**Pull request by glasseyes42**

### CODE REVIEW

**Comment by elgs** [comment]
Why do you want multiple ptr records against a single ip?

**Comment by glasseyes42** [comment]
I discovered it was a valid situation to get into - I'd imagine its not ideal in a lot of situations. However a colleague pointed out it could occur in the scenario of multiple domains on a single host ip. I too was somewhat vexed until I thought about it in a domain sense rather than x & y hosts.

**Comment by elgs** [comment]
I see. Just to clarify, in your code:
```javascript
if (urrTokens.lastIndexOf('PTR') == 0 && recordsSoFar[recordsSoFar.length - 1])
+          rrTokens.unshift(recordsSoFar[recordsSoFar.length - 1].name);
```

If multiple ptr records are against the same ip, you are returning the last ptr, and skip all previous, as oppose to returning all of them? Is my understanding correct?

**Comment by glasseyes42** [comment]
Yes. In the event of a PTR record not having an actual value, it seems to be a shorthand/alias for the last known PTR. For example:

```
$ORIGIN 30.168.192.in-addr.arpa.
3	PTR	HOST3.MYDOMAIN.COM.
4	PTR	HOST4.MYDOMAIN.COM.
	PTR HOST5.MYDOMAIN.COM.
	PTR HOST6.MYDOMAIN.COM.
5      PTR HOST7.MYDOMAIN.COM.
```

Host4, host5 & Host6 will all point to 192.168.30.4. 

The if statement is doing the check for if PTR was the first token found, and with a simple guard statement in case for _some_ reason our first PTR record has no leading value (Not sure what to actually do in that situation but I'd imagine its invalid).
After that its just left-pushing the 'name' (value) of the previous record into the tokens array so as to maintain the further logic based on token positions.

**Comment by elgs** [comment]
I got it. Thank you Chris.

**Comment by glasseyes42** [comment]
Thanks :) 

(in case you wonder what on earth i'm up to - needing to wrap bind9 up for our app-support team since moving away from powerdns)

**Comment by elgs** [comment]
That's awesome! :) Thanks for letting me know how it is useful for you.
Now `npm` and `bower` are updated.

**Pull request merged**
