### PR TITLE
Add compatability for changing origin in reverse lookup

### PR DESCRIPTION
**Pull request by glasseyes42**
My example used in the test might not be the best, but my use case is that I've a reverse zone responsible for say, 20.10.in-addr.arpa. 
Leading to a zone file like: 
```
$ORIGIN 20.10.in-addr.arpa.
$TTL 6000       ; 1 hour 40 minutes
1.1                     PTR     dog1.george.orwell.animal.farm.
10.10                   PTR     horse1.george.orwell.animal.farm.
$ORIGIN 30.20.10.in-addr.arpa.
$TTL 604800     ; 1 week
1                       PTR     cow1.george.orwell.animal.farm.
```
The return from parsing this right now would leave you with the final ```$origin``` line, and ```name``` properties that will only have ```1.1```. 
So, I propose adding (for ptr's only) another property ```fullname``` to enable backwards compatibility, which joins the ```$origin``` currently in use.

So now, for example, you would get returned:
```json
[ 
  { 
    "name": "1.1",
    "fullname": "1.1.20.10.IN-ADDR.ARPA.",
    "host": "dog1.george.orwell.animal.farm."
  },
  { 
    "name": "10.10",
    "fullname": "10.10.20.10.IN-ADDR.ARPA.",
    "host": "horse1.george.orwell.animal.farm."
  },
  { 
    "name": "1",
    "fullname": "1.30.20.10.IN-ADDR.ARPA.",
    "host": "cow1.george.orwell.animal.farm."
  }
]    
```
Thanks,

Chris.

### CODE REVIEW

**Comment by elgs** [comment]
Chris, thanks for your contribution. Please let me know if you want me to push your changes to the `npm` and `bower` immediately or not?

**Comment by glasseyes42** [comment]
A push to npm would be great, saves me linking until you do.

**Comment by glasseyes42** [comment]
And no problem, I had a stab and writing one of these about a year ago and gave up. The need re-arose and your library is working a treat! Thanks.

**Comment by elgs** [comment]
Thanks Chris. I have pushed your changes to the `npm` and `bower`.

**Pull request merged**
