### PR TITLE
Add CAA support

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by elgs** [comment]
Sorry for the late reply. I will look into it and get back soon.

**Comment by elgs** [comment]
When I ran:
`$ ./bin/zonefile -g test/zonefile_forward.json`
I got:
```
; CAA Records
@	0 issue "ca.example.net; policy=ev"
@	0 iodef "mailto:security@example.com"
@	0 iodef "http://iodef.example.com/"
```

It seems between @ and 0, `CAA` is missing?

**Comment by ad-m** [comment]
@elgs, you are right! Fixed!

```
$ nodejs test.js 
########## Generating forward zone file from JSON ##########
; Zone: MYDOMAIN.COM.
; Exported  (yyyy-mm-ddThh:mm:ss.sssZ): 2019-09-08T22:16:05.165Z

$ORIGIN MYDOMAIN.COM.
$TTL 3600

; SOA Record
@	 		IN	SOA	NS1.NAMESERVER.NET.	HOSTMASTER.MYDOMAIN.COM.	(
1567980965	 ;serial
3600	 ;refresh
600	 ;retry
604800	 ;expire
86400	 ;minimum ttl
)

; NS Records
@	IN	NS	NS1.NAMESERVER.NET.
@	IN	NS	NS2.NAMESERVER.NET.

; MX Records
@	IN	MX	0	mail1
@	IN	MX	10	mail2

; A Records
@	IN	A	127.0.0.1
www	IN	A	127.0.0.1
mail	IN	A	127.0.0.1

; AAAA Records
@	IN	AAAA	::1
mail	IN	AAAA	2001:db8::1

; CNAME Records
mail1	IN	CNAME	mail
mail2	IN	CNAME	mail

; PTR Records

; TXT Records

; SRV Records

; SPF Records

; CAA Records
@	CAA 0 issue "ca.example.net; policy=ev"
@	CAA 0 iodef "mailto:security@example.com"
@	CAA 0 iodef "http://iodef.example.com/"


########## Generating reverse zone file from JSON ##########
; Zone: 0.168.192.IN-ADDR.ARPA.
; Exported  (yyyy-mm-ddThh:mm:ss.sssZ): 2019-09-08T22:16:05.165Z

$ORIGIN 0.168.192.IN-ADDR.ARPA.
$TTL 3600

; SOA Record
@	 		IN	SOA	NS1.NAMESERVER.NET.	HOSTMASTER.MYDOMAIN.COM.	(
1567980965	 ;serial
3600	 ;refresh
600	 ;retry
604800	 ;expire
86400	 ;minimum ttl
)

; NS Records
@	IN	NS	NS1.NAMESERVER.NET.
@	IN	NS	NS2.NAMESERVER.NET.

; MX Records

; A Records

; AAAA Records

; CNAME Records

; PTR Records
1	IN	PTR	HOST1.MYDOMAIN.COM.
2	IN	PTR	HOST2.MYDOMAIN.COM.

; TXT Records

; SRV Records

; SPF Records

; CAA Records


########## Generating reverse zone file (IPv6) from JSON ##########
; Zone: 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa.
; Exported  (yyyy-mm-ddThh:mm:ss.sssZ): 2019-09-08T22:16:05.166Z

$ORIGIN 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa.
$TTL 3600

; SOA Record
@	 		IN	SOA	NS1.NAMESERVER.NET.	HOSTMASTER.MYDOMAIN.COM.	(
1567980965	 ;serial
3600	 ;refresh
600	 ;retry
604800	 ;expire
86400	 ;minimum ttl
)

; NS Records
@	IN	NS	NS1.NAMESERVER.NET.
@	IN	NS	NS2.NAMESERVER.NET.

; MX Records

; A Records

; AAAA Records

; CNAME Records

; PTR Records
1	IN	PTR	HOST1.MYDOMAIN.COM.
2	IN	PTR	HOST2.MYDOMAIN.COM.

; TXT Records

; SRV Records

; SPF Records

; CAA Records


########## Parsing forward zone file to JSON ##########
{
  '$origin': 'MYDOMAIN.COM.',
  '$ttl': '3600',
  soa: {
    name: '@',
    minimum: 86400,
    expire: 604800,
    retry: 600,
    refresh: 3600,
    serial: 1406291485,
    rname: 'HOSTMASTER.MYDOMAIN.COM.',
    mname: 'NS1.NAMESERVER.NET.'
  },
  ns: [
    { name: '@', host: 'NS1.NAMESERVER.NET.' },
    { name: '@', host: 'NS2.NAMESERVER.NET.' }
  ],
  mx: [
    { name: '@', preference: 0, host: 'mail1' },
    { name: '@', preference: 10, host: 'mail2' }
  ],
  a: [
    { name: '@', ip: '2.2.2.2' },
    { name: '@', ip: '1.1.1.1' },
    { name: '@', ip: '127.0.0.1' },
    { name: 'www', ip: '127.0.0.1' },
    { name: 'mail', ip: '127.0.0.1' },
    { name: 'mail', ip: '1.2.3.4' },
    { name: 'tst', ip: '101.228.10.12', ttl: 300 }
  ],
  aaaa: [ { name: '@', ip: '::1' }, { name: 'mail', ip: '2001:db8::1' } ],
  caa: [
    { name: '@', flags: 0, tag: 'issue', value: 'ca.example.net' },
    {
      name: '@',
      flags: 0,
      tag: 'iodef',
      value: 'mailto:security@example.com'
    },
    {
      name: '@',
      flags: 0,
      tag: 'iodef',
      value: 'http://iodef.example.com/'
    }
  ],
  cname: [
    { name: 'mail1', alias: 'mail' },
    { name: 'mail2', alias: 'mail' }
  ],
  spf: [
    { name: 'test', data: '"v=spf1" "mx:gcloud-node.com." "-all"' },
    { name: 'test1', data: '"v=spf2" "mx:gcloud-node.com." "-all"' },
    {
      name: 'test1',
      data: '"v=spf3" "mx:gcloud-node.com." "-all    "'
    },
    { name: 'test1', data: '"v=spf4" "mx:gcloud-node.com." "-all"' }
  ],
  txt: [
    {
      name: 'treefrog.ca.',
      txt: '"v=spf1 a mx a:mail.treefrog.ca a:webmail.treefrog.ca ip4:76.75.250.33 ?all"'
    },
    { name: 'treemonkey.ca.', txt: '"v=DKIM1\\; k=rsa\\; p=MIGf..."' },
    { name: 'treemonkey1.ca.', txt: '"v=DKIM1\\; k=rsa\\; p=MIGf..."' }
  ]
}


########## Parsing reverse zone file to JSON ##########
{
  '$origin': '168.192.in-addr.arpa.',
  '$ttl': '3600',
  soa: {
    name: '@',
    minimum: 86400,
    expire: 604800,
    retry: 600,
    refresh: 3600,
    serial: 1406291485,
    rname: 'HOSTMASTER.MYDOMAIN.COM.',
    mname: 'NS1.NAMESERVER.NET.'
  },
  ns: [
    { name: '@', host: 'NS1.NAMESERVER.NET.' },
    { name: '@', host: 'NS2.NAMESERVER.NET.' }
  ],
  ptr: [
    {
      name: '1',
      fullname: '1.0.168.192.IN-ADDR.ARPA.',
      host: 'HOST1.MYDOMAIN.COM.'
    },
    {
      name: '2',
      fullname: '2.0.168.192.IN-ADDR.ARPA.',
      host: 'HOST2.MYDOMAIN.COM.'
    },
    {
      name: '3',
      fullname: '3.30.168.192.in-addr.arpa.',
      host: 'HOST3.MYDOMAIN.COM.'
    },
    {
      name: '4',
      fullname: '4.30.168.192.in-addr.arpa.',
      host: 'HOST4.MYDOMAIN.COM.'
    },
    {
      name: '4',
      fullname: '4.30.168.192.in-addr.arpa.',
      host: 'HOST5.MYDOMAIN.COM.'
    },
    {
      name: '4',
      fullname: '4.30.168.192.in-addr.arpa.',
      host: 'HOST6.MYDOMAIN.COM.'
    },
    {
      name: '10.3',
      fullname: '10.3.168.192.in-addr.arpa.',
      host: 'HOST3.MYDOMAIN.COM.'
    },
    {
      name: '10.4',
      fullname: '10.4.168.192.in-addr.arpa.',
      host: 'HOST4.MYDOMAIN.COM.'
    }
  ]
}


########## Parsing reverse zone file (IPv6) to JSON ##########
{
  '$origin': '0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa.',
  '$ttl': '3600',
  soa: {
    name: '@',
    minimum: 86400,
    expire: 604800,
    retry: 600,
    refresh: 3600,
    serial: 1406291485,
    rname: 'HOSTMASTER.MYDOMAIN.COM.',
    mname: 'NS1.NAMESERVER.NET.'
  },
  ns: [
    { name: '@', host: 'NS1.NAMESERVER.NET.' },
    { name: '@', host: 'NS2.NAMESERVER.NET.' }
  ],
  ptr: [
    {
      name: '1',
      fullname: '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa.',
      host: 'HOST1.MYDOMAIN.COM.'
    },
    {
      name: '2',
      fullname: '2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa.',
      host: 'HOST2.MYDOMAIN.COM.'
    }
  ]
}
```

**Comment by elgs** [comment]
Thank you.

**Pull request merged**
